[package]
name = "data_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.0"
logging = { path = "../logging" }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
config = { path = "../config" }