/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PackageListComponent: typeof import('./components/PackageListComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./components/SidebarComponent.vue')['default']
  }
}
